apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuong_project4
spec:
  selector:
    matchLabels:
      name: cuong_project4
  template:
    metadata:
      labels:
        name: cuong_project4
    spec:
      containers:
      - name: cuong_project4
        image: 374000545310.dkr.ecr.us-east-1.amazonaws.com/project4:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: secret_project4


