apiVersion: v1
kind: Service
metadata:
  name: cuong_project4
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30039
      name: port-npt-kube
      protocol: TCP
  selector:
    name: webcuong_project4

